[build]
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[build.environment]
  SECRETS_SCAN_OMIT_KEYS = "ID_DE_PROYECTO_DE_FUEGO_BASE"
  SECRETS_SCAN_SMART_DETECTION_ENABLED = "false"

[[redirects]]
  from = "/ical/:cabina"
  to = "/.netlify/functions/ical-feed?cabin=:cabina"
  status = 200
  force = true
